version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
  build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install 
  post_build:
    commands:
      - echo Build completed✅
artifacts:
  files:
    - '**/*'
    - deploy_scripts/*.sh
    - appspec.yml